name: MLOps Pipeline CI/CD

on:
  push:
    branches: [ docker_ci ]
  pull_request:
    branches: [ docker_ci ]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train.py

    - name: Verify model files exist
      run: |
        ls -la 
        test -f linear_regression.joblib

    - name: Build Docker image
      run: |
        docker build -t housing-predictor:latest .

    - name: Test Docker container
      run: |
        docker run --rm housing-predictor:latest python src/predict.py

    - name: Login to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push to Docker Hub
      if: success()
      run: |
        docker tag housing-predictor:latest ${{ secrets.DOCKER_HUB_USERNAME }}/housing-predictor:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/housing-predictor:latest
        echo "Docker image pushed successfully!"