name: CI/CD Pipeline

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: python train.py
    
    - name: Build Docker image
      run: docker build -t yourdockerhubusername/mlops-assignment3 .
    
    - name: Run Docker container
      run: docker run yourdockerhubusername/mlops-assignment3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push to Docker Hub
      run: docker push yourdockerhubusername/mlops-assignment3